import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const cliPkgPath = path.resolve(here, "../../cli/package.json");
const outPath = path.resolve(here, "../src/data/version.ts");

let version = "0.0.0";
try {
  const cliPkg = JSON.parse(await fs.readFile(cliPkgPath, "utf8"));
  version = cliPkg.version;
} catch (err) {
  console.warn(
    `[sync-version] could not read ${cliPkgPath} — keeping fallback "${version}". ${err.message}`
  );
}

const content = `// AUTO-GENERATED by scripts/sync-version.mjs — do not edit by hand.
// Run \`npm run sync-version\` or any \`dev\`/\`build\` to refresh from cli/package.json.
export const CLI_VERSION = "${version}";
`;

await fs.writeFile(outPath, content, "utf8");
console.log(
  `[sync-version] CLI_VERSION="${version}" → ${path.relative(process.cwd(), outPath)}`
);
